worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 8080;
        server_name localhost;

        root /usr/share/nginx/html;

        location /momo-store/ {
            alias /usr/share/nginx/html/momo-store/;
            try_files $uri $uri/ /momo-store/index.html;
        }

        location = / {
            return 302 /momo-store/;
        }

        location /health {
            access_log off;
            default_type text/plain;
            return 200 'ok';
        }
    }
}
